# -*- coding: utf-8 -*-
"""QuantBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b8WpBBj6y5C_saa10HcZy0ZxzoUnR-f3
"""

import yfinance as yf
import pandas as pd
import numpy as np
import requests
import time
import warnings

# Limpieza de warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# --- CONFIGURACIÓN DE USUARIO ---
TOKEN = "7870474025:AAHY0C719LcKjRY7chOi-_THYh8woDYYiQo"
CHAT_ID = "1275255989"
RIESGO_USD = 100

def calcular_estrategia_final(ticker, riesgo_usd):
    """Calcula indicadores y genera la señal con el SL adaptativo."""
    try:
        df = yf.download(ticker, period="3y", auto_adjust=True, progress=False)
        if df.empty or len(df) < 200: return None

        # SMA 200
        df['SMA_200'] = df['Close'].rolling(window=200).mean()

        # RSI Wilder (Suavizado)
        delta = df['Close'].diff()
        gain = (delta.where(delta > 0, 0)).ewm(alpha=1/14, adjust=False).mean()
        loss = (-delta.where(delta < 0, 0)).ewm(alpha=1/14, adjust=False).mean()
        df['RSI'] = 100 - (100 / (1 + (gain / loss)))

        # ATR (Volatilidad)
        high_low = df['High'] - df['Low']
        high_cp = abs(df['High'] - df['Close'].shift())
        low_cp = abs(df['Low'] - df['Close'].shift())
        df['TR'] = pd.concat([high_low, high_cp, low_cp], axis=1).max(axis=1)
        df['ATR'] = df['TR'].rolling(window=14).mean()

        # Valores Actuales
        last = df.iloc[-1]
        precio = float(last['Close'].item())
        rsi = float(last['RSI'].item())
        sma = float(last['SMA_200'].item())
        atr = float(last['ATR'].item())
        max_14 = float(df['High'].rolling(window=14).max().iloc[-1])

        # --- LÓGICA DE STOP LOSS DINÁMICO (EL "PARCHE" DE AAPL) ---
        stop_teorico = max_14 - (atr * 3)
        if stop_teorico >= precio:
            stop_loss = precio - (atr * 1.5)
        else:
            stop_loss = stop_teorico

        # Gestión de Riesgo
        distancia = precio - stop_loss
        tp = precio + (distancia * 2)
        unidades = riesgo_usd / distancia if distancia > 0 else 0

        # Determinación de Señal
        senal = "🖐🏾 ESPERAR"
        if precio > sma:
            if rsi < 40: senal = "🟢 COMPRA"
            elif rsi > 70: senal = "🔴 VENTA"
        else:
            senal = "⚪ TEND. BAJISTA"

        return {
            "Ticker": ticker.replace("-USD", ""),
            "Precio": round(precio, 2),
            "RSI": round(rsi, 1),
            "SL": round(stop_loss, 2),
            "TP": round(tp, 2),
            "Cant": round(unidades, 2) if unidades > 0 else 0,
            "SEÑAL": senal
        }
    except Exception as e:
        print(f"Error analizando {ticker}: {e}")
        return None

def enviar_telegram(mensaje):
    """Envía el mensaje a la API de Telegram."""
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    payload = {"chat_id": CHAT_ID, "text": mensaje, "parse_mode": "Markdown"}
    try:
        requests.post(url, json=payload)
    except Exception as e:
        print(f"Error de conexión con Telegram: {e}")

# --- BLOQUE DE EJECUCIÓN PRINCIPAL ---
tickers = ['QQQ', 'NVDA', 'AAPL', 'MSFT', 'BTC-USD', 'ETH-USD', 'TSLA', 'AMD']
print(f"🚀 Iniciando escaneo Quant a las {time.strftime('%H:%M:%S')}...\n")

resultados_lista = []

for t in tickers:
    data = calcular_estrategia_final(t, RIESGO_USD)

    if data:
        resultados_lista.append(data)
        # Mostrar en consola para control
        print(f"📊 {data['Ticker']}: RSI {data['RSI']} | Señal: {data['SEÑAL']}")

        # DISPARAR ALERTA SI ES COMPRA
        if data['SEÑAL'] == "🟢 COMPRA":
            mensaje = (f"🎯 *¡SEÑAL DE COMPRA QUANT!*\n\n"
                       f"📈 *Activo:* {data['Ticker']}\n"
                       f"💰 *Precio:* ${data['Precio']}\n"
                       f"📊 *RSI:* {data['RSI']}\n\n"
                       f"🛡️ *Stop Loss:* {data['SL']}\n"
                       f"🚀 *Take Profit:* {data['TP']}\n"
                       f"⚖️ *Cantidad:* {data['Cant']} unidades\n\n"
                       f"_Riesgo por operación: ${RIESGO_USD}_")
            enviar_telegram(mensaje)
            print(f"   ✅ Mensaje enviado a Telegram para {t}")

print("\n--- RESUMEN FINAL ---")
print(pd.DataFrame(resultados_lista).to_string(index=False))
print("\n✅ Proceso finalizado.")